import { DiscoverProfile, Conversation } from '../types';

// Mock profiles for discovery
export const mockProfiles: DiscoverProfile[] = [
  {
    id: '1',
    name: 'Nguyễn Minh Anh',
    university: 'Đại học Bách Khoa Hà Nội',
    major: 'Khoa học Máy tính',
    year: 4,
    role: 'mentor',
    bio: 'Đam mê giúp đỡ sinh viên bước vào ngành công nghệ. Cựu thực tập sinh SWE tại Google.',
    interests: ['Công nghệ', 'Tư vấn nghề nghiệp', 'Lập trình'],
    images: ['https://i.pravatar.cc/300?img=1'],
    category: 'technology',
    willMatch: true,
  },
  {
    id: '2',
    name: 'Trần Hoàng Long',
    university: 'Đại học Kinh tế TP.HCM',
    major: 'Tài chính',
    year: 3,
    role: 'mentor',
    bio: 'Đam mê tài chính với kinh nghiệm thực tập tại Goldman Sachs. Rất vui được hướng dẫn bạn!',
    interests: ['Tài chính', 'Ngân hàng đầu tư', 'Chứng khoán'],
    images: ['https://i.pravatar.cc/300?img=12'],
    category: 'finance',
  },
  {
    id: '3',
    name: 'Lê Thanh Hương',
    university: 'Đại học Khoa học Xã hội và Nhân văn',
    major: 'Triết học',
    year: 2,
    role: 'mentor',
    bio: 'Yêu thích thảo luận về đạo đức, chủ nghĩa hiện sinh và các câu hỏi về cuộc sống. Cùng khám phá ý tưởng nhé!',
    interests: ['Triết học', 'Đạo đức', 'Tư duy phản biện'],
    images: ['https://i.pravatar.cc/300?img=5'],
    category: 'philosophy',
    willMatch: false,
  },
  {
    id: '4',
    name: 'Phạm Đức Anh',
    university: 'Đại học FPT',
    major: 'Truyền thông Đa phương tiện',
    year: 4,
    role: 'mentor',
    bio: 'Nhà sáng tạo nội dung và chuyên gia chiến lược mạng xã hội. Có thể giúp bạn xây dựng thương hiệu cá nhân!',
    interests: ['Truyền thông', 'Sáng tạo nội dung', 'Marketing'],
    images: ['https://i.pravatar.cc/300?img=15'],
    category: 'media',
  },
  {
    id: '5',
    name: 'Võ Thị Mai',
    university: 'Đại học Luật Hà Nội',
    major: 'Luật học',
    year: 3,
    role: 'mentor',
    bio: 'Sinh viên luật với kinh nghiệm trong các phiên tòa giả định. Để tôi giúp bạn chuẩn bị cho trường luật!',
    interests: ['Luật', 'Tranh luận', 'Hùng biện'],
    images: ['https://i.pravatar.cc/300?img=9'],
    category: 'law',
    willMatch: true,
  },
  {
    id: '6',
    name: 'Đặng Quốc Việt',
    university: 'Đại học Ngoại thương',
    major: 'Quản trị Kinh doanh',
    year: 4,
    role: 'mentor',
    bio: 'Người sáng lập startup và đam mê chiến lược kinh doanh. Luôn sẵn lòng thảo luận về khởi nghiệp!',
    interests: ['Kinh doanh', 'Khởi nghiệp', 'Chiến lược'],
    images: ['https://i.pravatar.cc/300?img=13'],
    category: 'business',
  },
  {
    id: '7',
    name: 'Hoàng Thị Lan',
    university: 'Đại học Y Hà Nội',
    major: 'Y khoa',
    year: 3,
    role: 'mentor',
    bio: 'Sinh viên y với kinh nghiệm nghiên cứu. Có thể hướng dẫn bạn trên con đường vào trường y!',
    interests: ['Khoa học', 'Y học', 'Nghiên cứu'],
    images: ['https://i.pravatar.cc/300?img=20'],
    category: 'science',
  },
  {
    id: '8',
    name: 'Bùi Minh Tuấn',
    university: 'Đại học Mỹ thuật Việt Nam',
    major: 'Mỹ thuật Số',
    year: 2,
    role: 'mentor',
    bio: 'Nghệ sĩ kỹ thuật số và nhà thiết kế. Cùng nhau tạo ra điều gì đó tuyệt vời nào!',
    interests: ['Nghệ thuật', 'Thiết kế', 'Sáng tạo'],
    images: ['https://i.pravatar.cc/300?img=33'],
    category: 'arts',
  },
];

// Mock conversations
export const mockConversations: Conversation[] = [
  {
    id: '1',
    partnerId: '1',
    partnerName: 'Nguyễn Minh Anh',
    partnerRole: 'mentor',
    partnerImage: 'https://i.pravatar.cc/300?img=1',
    category: 'Công nghệ',
    messages: [
      {
        id: '1',
        senderId: '1',
        text: 'Chào bạn! Cảm ơn đã kết nối. Mình có thể giúp gì cho hành trình công nghệ của bạn?',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: '2',
        senderId: 'current-user',
        text: 'Chào Minh Anh! Mình muốn tìm hiểu về các vị trí thực tập kỹ sư phần mềm.',
        timestamp: new Date(Date.now() - 3000000).toISOString(),
      },
      {
        id: '3',
        senderId: '1',
        text: 'Tuyệt! Mình rất vui được chia sẻ kinh nghiệm. Bạn muốn chat khi nào?',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
      },
    ],
    hasUnread: true,
    isArchived: false,
    lastMessage: 'Tuyệt! Mình rất vui được chia sẻ kinh nghiệm. Bạn muốn chat khi nào?',
    lastMessageTime: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: '2',
    partnerId: '5',
    partnerName: 'Võ Thị Mai',
    partnerRole: 'mentor',
    partnerImage: 'https://i.pravatar.cc/300?img=9',
    category: 'Luật',
    messages: [
      {
        id: '1',
        senderId: '5',
        text: 'Xin chào! Rất vui được giúp bạn chuẩn bị cho trường luật!',
        timestamp: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: '2',
        senderId: 'current-user',
        text: 'Cảm ơn chị! Em có một số câu hỏi về kỳ thi đầu vào.',
        timestamp: new Date(Date.now() - 82800000).toISOString(),
      },
    ],
    scheduledSession: {
      id: 's1',
      datetime: new Date(Date.now() + 172800000).toISOString(),
      confirmed: true,
    },
    hasUnread: false,
    isArchived: false,
    lastMessage: 'Cảm ơn chị! Em có một số câu hỏi về kỳ thi đầu vào.',
    lastMessageTime: new Date(Date.now() - 82800000).toISOString(),
  },
];
