import { DiscoverProfile, Conversation } from '../types';

// Mock profiles for discovery
export const mockProfiles: DiscoverProfile[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    university: 'Stanford University',
    major: 'Computer Science',
    year: 4,
    role: 'mentor',
    bio: 'Passionate about helping students break into tech. Former SWE intern at Google.',
    interests: ['Technology', 'Career Advice', 'Coding'],
    images: ['https://i.pravatar.cc/300?img=1'],
    category: 'technology',
    willMatch: true,
  },
  {
    id: '2',
    name: 'Michael Rodriguez',
    university: 'MIT',
    major: 'Finance',
    year: 3,
    role: 'mentor',
    bio: 'Finance enthusiast with internship experience at Goldman Sachs. Happy to guide!',
    interests: ['Finance', 'Investment Banking', 'Stock Market'],
    images: ['https://i.pravatar.cc/300?img=12'],
    category: 'finance',
  },
  {
    id: '3',
    name: 'Emily Watson',
    university: 'Harvard University',
    major: 'Philosophy',
    year: 2,
    role: 'mentor',
    bio: 'Love discussing ethics, existentialism, and life questions. Let\'s explore ideas together!',
    interests: ['Philosophy', 'Ethics', 'Critical Thinking'],
    images: ['https://i.pravatar.cc/300?img=5'],
    category: 'philosophy',
    willMatch: false,
  },
  {
    id: '4',
    name: 'David Kim',
    university: 'UC Berkeley',
    major: 'Media Studies',
    year: 4,
    role: 'mentor',
    bio: 'Content creator and social media strategist. Can help with personal branding!',
    interests: ['Media', 'Content Creation', 'Marketing'],
    images: ['https://i.pravatar.cc/300?img=15'],
    category: 'media',
  },
  {
    id: '5',
    name: 'Jessica Liu',
    university: 'Yale University',
    major: 'Pre-Law',
    year: 3,
    role: 'mentor',
    bio: 'Aspiring lawyer with experience in mock trials. Let me help you with law school prep!',
    interests: ['Law', 'Debate', 'Public Speaking'],
    images: ['https://i.pravatar.cc/300?img=9'],
    category: 'law',
    willMatch: true,
  },
  {
    id: '6',
    name: 'Alex Thompson',
    university: 'UCLA',
    major: 'Business Administration',
    year: 4,
    role: 'mentor',
    bio: 'Startup founder and business strategy nerd. Always happy to discuss entrepreneurship!',
    interests: ['Business', 'Entrepreneurship', 'Strategy'],
    images: ['https://i.pravatar.cc/300?img=13'],
    category: 'business',
  },
  {
    id: '7',
    name: 'Olivia Martinez',
    university: 'Brown University',
    major: 'Biology',
    year: 3,
    role: 'mentor',
    bio: 'Pre-med student with research experience. Can guide you through the medical school journey!',
    interests: ['Science', 'Medicine', 'Research'],
    images: ['https://i.pravatar.cc/300?img=20'],
    category: 'science',
  },
  {
    id: '8',
    name: 'Ryan Patel',
    university: 'Cornell University',
    major: 'Fine Arts',
    year: 2,
    role: 'mentor',
    bio: 'Digital artist and designer. Let\'s create something amazing together!',
    interests: ['Arts', 'Design', 'Creativity'],
    images: ['https://i.pravatar.cc/300?img=33'],
    category: 'arts',
  },
];

// Mock conversations
export const mockConversations: Conversation[] = [
  {
    id: '1',
    partnerId: '1',
    partnerName: 'Sarah Chen',
    partnerRole: 'mentor',
    partnerImage: 'https://i.pravatar.cc/300?img=1',
    category: 'Technology',
    messages: [
      {
        id: '1',
        senderId: '1',
        text: 'Hi! Thanks for connecting. How can I help you with your tech journey?',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: '2',
        senderId: 'current-user',
        text: 'Hi Sarah! I\'m interested in learning about software engineering internships.',
        timestamp: new Date(Date.now() - 3000000).toISOString(),
      },
      {
        id: '3',
        senderId: '1',
        text: 'Great! I\'d be happy to share my experience. When would you like to chat?',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
      },
    ],
    hasUnread: true,
    isArchived: false,
    lastMessage: 'Great! I\'d be happy to share my experience. When would you like to chat?',
    lastMessageTime: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: '2',
    partnerId: '5',
    partnerName: 'Jessica Liu',
    partnerRole: 'mentor',
    partnerImage: 'https://i.pravatar.cc/300?img=9',
    category: 'Law',
    messages: [
      {
        id: '1',
        senderId: '5',
        text: 'Hello! Excited to help you with law school preparation!',
        timestamp: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: '2',
        senderId: 'current-user',
        text: 'Thank you! I have some questions about the LSAT.',
        timestamp: new Date(Date.now() - 82800000).toISOString(),
      },
    ],
    scheduledSession: {
      id: 's1',
      datetime: new Date(Date.now() + 172800000).toISOString(),
      confirmed: true,
    },
    hasUnread: false,
    isArchived: false,
    lastMessage: 'Thank you! I have some questions about the LSAT.',
    lastMessageTime: new Date(Date.now() - 82800000).toISOString(),
  },
];
